# Generated by Django 5.2.2 on 2025-06-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('parameter', models.CharField(choices=[('temperature', 'Temperature'), ('salinity', 'Salinity'), ('oxygen', 'Dissolved Oxygen'), ('chlorophyll', 'Chlorophyll')], max_length=50)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('mpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='dto.mpazones')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['mpa', 'timestamp', 'parameter'], name='dto_timeser_mpa_id_fb8039_idx')],
            },
        ),
    ]
